### PR TITLE
fix java doc as mention in spec

### PR DESCRIPTION
**Pull request by dvrajitha**
Please check this

### CODE REVIEW

**Comment by sublimator** [comment]
Life! :)

**Comment by sappenin** [comment]
@dvrajitha Looks like something changed on the circleCI side so the builds aren't working. Once https://github.com/hyperledger/quilt/pull/180 is merged, can you rebase and try your build again?

**Comment by sappenin** [comment]
@dvrajitha nm - looks like I could do it right from github...

**Comment by dvrajitha** [comment]
@sappenin Thank you!..

**Pull request merged**
