### PR TITLE
[crypto-conditions] Fix Javadoc errors #5

### PR DESCRIPTION
**Pull request by rizwantanoli**
Cleaned-up Javadoc warnings in build for crypto-conditions. See #5.
Signed-off-by: Rizwan Tanoli <contact@rizwantanoli.com>

### CODE REVIEW

**Comment by rizwantanoli** [comment]
@sappenin @adrianhopebailie sounds good. I will make the changes later tonight and recommit.

**Comment by adrianhopebailie** [comment]
@rizwantanoli this still seems to be broken for some reason. Sorry, that this is proving to be a PIA.

Can I suggest trying to rebase this on `upstream master` and squashing all your changes into a single commit then  pushing that up to `rizwantanoli:master` and see if that solves the issue.

If you are still struggling, let me know.

**Comment by rizwantanoli** [comment]
thanks Adrian for checking-in; I will spend sometime on it this evening and will reach out if it doesn't get resolved.


________________________________

**Comment by rizwantanoli** [comment]
@adrianhopebailie tried various things but no avail. I installed the checkstyle plugin for eclipse and ran that as well. It didn't give me any errors (warnings on some imports in some files not being in proper order) and the maven build for checkstyle ran successfully as well.
At this point, I am thinking it might have had something to do with how GitHub is maybe treating my line endings when checking-in/checking out or it could be encoding - although I didn't change any encoding options or settings.
I will go ahead and revert these changes and see if the diff only highlights what I changed vs. entire file

**Comment by adrianhopebailie** [comment]
@rizwantanoli that is weird. Could be line endings.

Try rebasing you changes on master too.

**Comment by sappenin** [comment]
@rizwantanoli You should be able to see this occur locally as well - just make a simple change and do a diff to see what's changed. Making a small change (like a single word) should not make the whole file change.

**Comment by sappenin** [comment]
Closing this. This has been fixed by more recent commits. See #5 for details.

**Pull request closed without merging**
