### PR TITLE
Fix code coverage…

### PR DESCRIPTION
**Pull request by sappenin**

### CODE REVIEW

**Comment by ryjones** [comment]
you'll probably need to do a squash at the end of the day to get the DCO working.

**Comment by rizwantanoli** [comment]
DCO is a pain, if not enabled initially; I got it to work by stashing away changes on my fork, removing the commits without DCO and forcing sync with master.

**Comment by adrianhopebailie** [comment]
@sappenin do you wanna squash on your local and force push a new signed commit to this branch to see if that fixes the DCO bot issue?

**Comment by sappenin** [comment]
I’ll pick this up tomorrow - sorry haven’t had a chance to give this some love. It’s a small change though so feel free to duplicate if anyone wants to get to it before I do.

**Comment by sappenin** [comment]
Closing this in-favor of #37.

**Pull request closed without merging**
