### PR TITLE
Fixes #2 Updates triggered on javadoc.io and linking documentation

### LINKED ISSUE #2: Publish Quilt JavaDocs
<a href="https://github.com/adrianhopebailie"></img></a> **Issue by [adrianhopebailie](https://github.com/adrianhopebailie)**
_Tuesday May 23, 2017 at 07:49 GMT_
_Originally opened as https://github.com/interledger/java-crypto-conditions/issues/48_

----

Need to add build script that publishes JavaDoc to /docs folder

### PR DESCRIPTION
**Pull request by sudheesh001**
- Javadoc links to hosted documentation for each module in `quilt`

Signed-off-by: Sudheesh Singanamalla <sudheesh@cs.washington.edu>

### CODE REVIEW

**Comment by sappenin** [comment]
@sudheesh001 Looks like we were doing the same thing at the same time. I like your formatting better, so will incorporate that into my PR.

**Comment by sudheesh001** [comment]
Ah the race conditions!! 😄 Sure, do let me know if you want me to make any changes to this or do you want to pull this into your local branch and merge it with your changes?

**Comment by sappenin** [comment]
No worries - I can pull your changes.

**Comment by sappenin** [comment]
Closing in-favor of #339

**Pull request closed without merging**
